---
title: "WHONDRS_microbe_data_manipulation"
author: "Casey McGrath"
date: "3/28/2022"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
```

```{r}
#Set the working directory 
setwd('C:/Users/mcgr323/projects/whondrs_microbes/')

#Load WHONDRS S19S data (presence/absence)
data <- read.csv('Processed_Clean_S19S_Water_Field_sediments_9-29_Data.csv')

#Load WHONDRS S19S molarity data 
mol <- read.csv('Processed_Clean_S19S_Water_Field_sediments_9-29_Mol.csv')

#Change column header 
names(data)[1] <- "Mass"

#Create ID column
data <- dplyr::mutate(data, ID = row_number())
mol <- dplyr::mutate(mol, ID = row_number())

#Subset mol to get df of just Mass and MolForm
mol_subset <- mol %>% select(ID, Mass, MolForm)

#Merge data and mol
df <- merge(data, mol_subset, by= "ID")
```

```{r}
#Select upstream sediment samples 
sed.upper.data = as.data.frame(cbind(df$Mass.x, df$MolForm, df[grep("Sed_Field_ICR.U",
                                   colnames(df))]))

#Select midstream sediment samples 
sed.mid.data = as.data.frame(cbind(df$Mass.x, df$MolForm, df[grep("Sed_Field_ICR.M",
                                   colnames(df))]))

#Select downstream sediment samples 
sed.lower.data = as.data.frame(cbind(df$Mass.x, df$MolForm, df[grep("Sed_Field_ICR.D",
                                   colnames(df))]))

#Change column names
names(sed.upper.data)[1] <- 'Mass'
names(sed.mid.data)[1] <- 'Mass'
names(sed.lower.data)[1] <- 'Mass'
names(sed.upper.data)[2] <- 'MolForm'
names(sed.mid.data)[2] <- 'MolForm'
names(sed.lower.data)[2] <- 'MolForm'

#Select upstream water samples 
water.upper.data = as.data.frame(cbind(df$Mass.x, df$MolForm, df[grep("ICR.1",
                                   colnames(df))]))

#Select midstream water samples 
water.mid.data = as.data.frame(cbind(df$Mass.x, df$MolForm, df[grep("ICR.2",
                                   colnames(df))]))

#Select downstream water samples 
water.lower.data = as.data.frame(cbind(df$Mass.x, df$MolForm, df[grep("ICR.3",
                                   colnames(df))]))

#Change column names
names(water.upper.data)[1] <- 'Mass'
names(water.mid.data)[1] <- 'Mass'
names(water.lower.data)[1] <- 'Mass'
names(water.upper.data)[2] <- 'MolForm'
names(water.mid.data)[2] <- 'MolForm'
names(water.lower.data)[2] <- 'MolForm'
```


```{r}
var_of_interest <- c('S19S_0069', 
'S19S_0070',
'S19S_0078', 
'S19S_0079',
'S19S_0065',
'S19S_0033',
'S19S_0007', 
'S19S_0008', 
'S19S_0032',
'S19S_0013',
'S19S_0014',
'S19S_0064',
'S19S_0054',
'S19S_0037',
'S19S_0052',
'S19S_0053_DS',
'S19S_0012',
'S19S_0072',
'S19S_0073',
'S19S_0084')

matches <- cbind(sed.upper.data$Mass, sed.upper.data$MolForm,sed.upper.data[unique(grep(paste(var_of_interest,collapse="|"), colnames(sed.upper.data), value=TRUE))])

  for (i in var_of_interest) {
    site.data = as.data.frame(cbind(sed.upper.data$Mass, sed.upper.data$MolForm, sed.upper.data[grep(i,colnames(sed.upper.data))]))
  
    site.subset = site.data[!(site.data[2]==0),]
    write.csv(site.subset,file=paste0("Sed_U_", i,".csv"))
  }



```


